repos:
  - repo: ankitects/anki
    labels:
      - good first issue
      - help wanted

  - repo: sillytavern/SillyTavern
    labels:
      - 👩‍💻 Good First Issue

  - repo: apache/mahout
    labels:
      - good first issue
