repos:
  - repo: ankitects/anki
    labels:
      - good first issue
      - help wanted

  - repo: sillytavern/SillyTavern
    labels:
      - good first issue

  - repo: apache/mahout
    labels:
      - good first issue
