name: send_discord

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord notification
        uses: stegzilla/discord-notify@v5
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: GitHub Issue Tracker
          message: |
            Hello from GitHub Actions 🚀
